spring:
  profiles:
    active: prod
  application:
    name: careerconnect

  # Database 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format_sql: true
      hibernate:
        dialect:
    hibernate:
      ddl-auto: update

  flyway:
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: classpath:/db/migration/mariadb
    baselineOnMigrate: true
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-sandbox
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


#log 설정
logging:
  config: classpath:logback-spring.xml
#  level:
#    root: DEBUG
#  pattern:
#     console: "%d %5p {%c} %m%n"

token:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

