spring:
  profiles:
    active: dev
  application:
    name: careerconnect

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  flyway:
    location: classpath:/db/migration/{vendor}
    baselineOnMigrate: true
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


#    # Database 설정
#    datasource:
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://localhost:3307/careerconnection_db?useUnicode=true&allowPublicKeyRetrieval=true
#      username: root
#      password: maria



  #database 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3307/careerconnection_db?useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: maria




#log 설정
logging:
  config: classpath:logback-spring.xml
#  level:
#    root: DEBUG
#  pattern:
#     console: "%d %5p {%c} %m%n"

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

