spring:
  profiles:
    active: dev
  application:
    name: careerconnect

  # Database 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3307}/${DB_DATABASE:boot_db}
    username: ${DB_USERNAME:boot}
    password: ${DB_PASSWORD:boot}

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate

  flyway:
    url: jdbc:mariadb://${DB_HOST:127.0.0.1}:${DB_PORT:3307}/${DB_DATABASE:boot_db}
    user: ${DB_USERNAME:boot}
    password: ${DB_PASSWORD:boot}
    locations: classpath:/db/migration/{vendor}
    baselineOnMigrate: true
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Log 설정
logging:
  config: classpath:logback-spring.xml
  level:
    root: DEBUG
#  pattern:
#    console: "%d %5p {%c} %m%n"

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12
